sudo: false
env:
  global:
    - CC_TEST_REPORTER_ID=ccb61f4c66dd4eadf6646e35d63dc123133dc37dabc0bd5eb0c002c21abe5628
language: ruby
rvm:
  - 2.2
  - 2.3
  - 2.4
services:
  - mongodb
before_install:
  - gem install bundler
  - gem update --system
  - gem --version
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rake test
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
