sudo: false
env:
  global:
    - CC_TEST_REPORTER_ID=ccb61f4c66dd4eadf6646e35d63dc123133dc37dabc0bd5eb0c002c21abe5628
language: ruby
rvm:
  - 2.2
  - 2.3
  - 2.4
  - 2.5
gemfile:
  - gemfiles/mongoid_61.gemfile
  - gemfiles/mongoid_60.gemfile
  - gemfiles/mongoid_51.gemfile
  - gemfiles/mongoid_50.gemfile
  - gemfiles/mongoid_40.gemfile
matrix:
  exclude:
    - rvm: 2.5
      gemfile: gemfiles/mongoid_51.gemfile
    - rvm: 2.5
      gemfile: gemfiles/mongoid_50.gemfile
    - rvm: 2.5
      gemfile: gemfiles/mongoid_40.gemfile
    - rvm: 2.4
      gemfile: gemfiles/mongoid_51.gemfile
    - rvm: 2.4
      gemfile: gemfiles/mongoid_50.gemfile
    - rvm: 2.4
      gemfile: gemfiles/mongoid_40.gemfile
    - rvm: 2.1
      gemfile: gemfiles/mongoid_61.gemfile
    - rvm: 2.0
      gemfile: gemfiles/mongoid_61.gemfile
    - rvm: 2.1
      gemfile: gemfiles/mongoid_60.gemfile
cache: bundler
services:
  - mongodb
before_install:
  - gem install bundler
  - gem update --system
  - gem --version
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rake test
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
